---
title: "R Notebook"
output: html_notebook
---

Let's import the generated data
```{r}
error_records <- read.csv(file="error_records.csv")
```
Now find the errors
```{r}
library(errorlocate)
library(validate)
library(dplyr)
library(mice)
rules <- validator(!((age =="0-5" | age == "6-12") & (marital != "Single")),
                   !(age == "60+" & relationship == "Child"),
                   !(relationship == "Spouse" & marital == "Single"),
                   !(age == "0-5" & education == "Post-Secondary"),
                   !((age == "0-5" | age == "6-12" | age == "13-18") & relationship == "Spouse"),
                   !(marital == "Widowed" & relationship == "Spouse"),
                   !(age == "0-5" & relationship == "Self"))

out <- confront(error_records,rules)
plot(out)

```
Now replace errors with NA
```{r}
dat <- replace_errors(error_records,rules,value="suggestion")

```


Now impute the errors
```{r}
dat <- subset(dat,select=-c(ids))

impute_data <- function(dat) {
 dat <- dat %>%
    mutate(
        age = as.factor(age),
        education = as.factor(education),
        marital = as.factor(marital),
        relationship = as.factor(relationship),
        sex = as.factor(sex),

    )
  init = mice(dat, meth="cart",maxit=5) 
  meth = init$method
  predM = init$predictorMatrix
  meth[c("education")]="polyreg"
  meth[c("age")]="polyreg"
  meth[c("marital")]="polyreg"
  meth[c("relationship")]="polyreg"
  meth[c("sex")]="polyreg"
  imputed = mice(dat, method=meth, predictorMatrix=predM, m=5)
  imputed <- complete(imputed)
  
  return (imputed)
}

imputed <- impute_data(dat)

```

What's the error rate for these new errors? 
```{r}
imputed_2 <- impute_data(replace_errors(imputed,rules,value="suggestion"))
out <- confront(imputed_2,rules)
plot(out)

```
```{r}
violating(imputed_2,rules)
```

